name: Code Analysis
description: Run code analysis using PMD

inputs:
  code-analysis-directory:
    description: Code analysis directory
  code-analysis-token:
    description: Code analysis token
  rulesets-path:
    description: Rulesets path
runs:
  using: "composite"
  steps:

    - uses: pmd/pmd-github-action@v1
      id: pmd
      with:
          version: '6.55.0'
          sourcePath: "${{ inputs.code-analysis-directory }}"
          token: "${{ inputs.code-analysis-token }}"
          rulesets: "${{ inputs.rulesets-path }}"
          analyzeModifiedFilesOnly: "flase"
        
          
