name: Code Analysis
description: Run code analysis using PMD

inputs:
  code-analysis-directory:
    description: Code analysis directory
  code-analysis-token:
    description: Code analysis token
  rulesets-path:
    description: Rulesets path
  results-format:
    description: Results format
runs:
  using: "composite"
  steps:

    - uses: pmd/pmd-github-action@v1
      id: pmd
      with:
          version: '6.55.0'
          sourcePath: "${{ inputs.code-analysis-directory }}"
          token: "${{ inputs.code-analysis-token }}"
          rulesets: "${{ inputs.rulesets-path }}"
          analyzeModifiedFilesOnly: "flase"
          createGitHubAnnotations: "true"
          
      - name: Generate HTML Report
        run: |
          "${{ github.workspace }}/pmd-bin-${{ steps.pmd.outputs.version }}/bin/run.sh" pmd \
            -f html \
            -r reports/pmd-analysis-report.html \
            -d "${{ secrets.SOURCE_DIR }}" \
            -R "${{ secrets.PATH_RULES }}" \
            -no-cache \
            -sarif-file "${{ github.workspace }}/pmd-report.sarif"
          
      - name: Upload PMD HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: pmd-html-report
          path: reports

        
