name: Code Analysis
description: Run code analysis using PMD

inputs:
  code-analysis-directory:
    description: Code analysis directory
  code-analysis-token:
    description: Code analysis token
  rulesets-path:
    description: Rulesets path
  results-format:
    description: Results format
runs:
  using: "composite"
  steps:

    - uses: pmd/pmd-github-action@v1
      id: pmd
      with:
          version: '6.55.0'
          sourcePath: "${{ inputs.code-analysis-directory }}"
          token: "${{ inputs.code-analysis-token }}"
          rulesets: "${{ inputs.rulesets-path }}"
          analyzeModifiedFilesOnly: "flase"
          createGitHubAnnotations: "true"
          
    - name: Setup PMD
      uses: legetz/setup-pmd@7.0.0-rc4
    - name: APEX full scan
      shell: bash
      run: pmd check --dir ${{ inputs.code-analysis-directory }} --rulesets ${{ inputs.rulesets-path }} --uploadSarifReport false -f html -r ${{ inputs.results-format }} || true

    - name: Upload PMD Report
      uses: actions/upload-artifact@v2
      with:
        name: pmd-report
        path: ${{ inputs.results-format }}


        
