name: Code Analysis
description: Run code analysis using PMD

inputs:
  code-analysis-directory:
    description: Code analysis directory
  code-analysis-token:
    description: Code analysis token
  rulesets-path:
    description: Rulesets path
  results-format:
    description: Results format
runs:
  using: "composite"
  steps:

    - uses: pmd/pmd-github-action@v1
      id: pmd
      with:
          version: '6.55.0'
          sourcePath: "${{ inputs.code-analysis-directory }}"
          token: "${{ inputs.code-analysis-token }}"
          rulesets: "${{ inputs.rulesets-path }}"
          analyzeModifiedFilesOnly: "flase"
          format: "${{ inputs.results-format }}"

    - name: Upload SARIF report
        uses: actions/upload-artifact@v2
        with:
          name: pmd-sarif-report
          path: /home/runner/work/ACTION-QA-Apex-PMD/pmd-report.sarif

      - name: View SARIF report
        uses: github/codeql-action/sarif-to-standalone-checks@v1

      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: pmd-html-report
          path: /home/runner/work/ACTION-QA-Apex-PMD/pmd-html-report
        
