name: Run Code Analysis

on:
    push:
      branches:
        - 'main'
      paths-ignore:
        - 'README.md'
        - '.github/workflows/**'

jobs:
    code-analysis:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            ref: main
            repository: KrishnaJallipalliQ/dummy-C-
            token: ${{ secrets.SERVICE_ACCOUNT_MERGE_TOKEN }}
            fetch-depth: 0
            path: /apex-recipes-main/force-app/main/default/classes/
        - uses: KrishnaJallipalliQ/ACTION-QA-Apex-PMD@main
          with:
            code-analysis-path: ${{ secrets.DIR_MAIN_PATH }}
            code-analysis-host-url: ${{ secrets.SONAR_HOST_URL }}

        - name: Upload PMD xml Report
          uses: actions/upload-artifact@v2
          with:
            name: pmd-report
            path: /home/runner/work/dummy-C-/pmd-report.xml --rulesets ./pmd-rules.xml -f xml -r /home/runner/work/dummy-C-/pmd-report.xml || true
